version: "3.0"

services:
  sonarqube-prometheus-exporter:
    build:
      context: .
    ports:
      - "9300:3000"
    environment:
      - SONARQUBE_URL=${SONARQUBE_URL}
      - SONARQUBE_TOKEN=${SONARQUBE_TOKEN}
    restart: always
